
@host=http://localhost:5000
@albumId=album-QDd631hwUSild-GUmMWKI
@songId=song-AxxIYoi_N6-vqfqXSaUiv

###
POST {{host}}/album HTTP/1.1
Content-Type: application/json

{
  "name": "Discovery",
  "year": 2020
}

###
GET {{host}}/album/{{albumId}} HTTP/1.1
Content-Type: application/json

###
PUT {{host}}/album/{{albumId}} HTTP/1.1
Content-Type: application/json

{
  "name": "Foo bar bazz",
  "year": 2013
}

###
DELETE {{host}}/album/{{albumId}} HTTP/1.1
Content-Type: application/json

###
GET {{host}}/songs?title=Bar&performer=Bazz HTTP/1.1
Content-Type: application/json

###
GET {{host}}/songs?title=mamamia HTTP/1.1
Content-Type: application/json

###
GET {{host}}/songs?performer=Bazz HTTP/1.1
Content-Type: application/json

###
GET {{host}}/songs HTTP/1.1
Content-Type: application/json

###
POST {{host}}/songs HTTP/1.1
Content-Type: application/json

{
  "title": "Mamamia lezatos",
  "year": 2011,
  "performer": "Mo isi apa ini",
  "genre": "Pop",
  "duration": 300,
  "albumId": "{{albumId}}"
}

###
POST {{host}}/songs HTTP/1.1
Content-Type: application/json

{
  "year": 2011,
  "performer": "Mo isi apa ini",
  "genre": "Pop",
  "duration": 300,
  "albumId": "{{albumId}}"
}

###
GET {{host}}/songs/{{songId}} HTTP/1.1
Content-Type: application/json

###
PUT {{host}}/songs/{{songId}} HTTP/1.1
Content-Type: application/json

{
  "title": "Taubah lezatos",
  "year": 2011,
  "performer": "Mo isi ini",
  "genre": "Rock",
  "duration": 100,
  "albumId": "{{albumId}}"
}

###
DELETE {{host}}/songs/{{songId}} HTTP/1.1
Content-Type: application/json
